name: transition_platform
description: A civic tech movement platform connecting citizens, students, and industrialists.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.2.0
  latlong2: ^0.9.1
  geolocator: ^13.0.2
  image_picker: ^1.1.2
  file_picker: ^8.1.6
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # To add assets (like the specific screenshots or icons later), 
  # uncomment the section below and add your file paths:
  # assets:
  #   - assets/images/